### ISSUE TITLE
Does this project have a license?

### ISSUE THREAD

**Issue by akirak** [ryantking/workshop#1]
Hello,

Thank you for this nice repository. I was looking for an example configuration for river compositor on NixOS and found yours. It is comprehensive and helped me get started with Wayland on NixOS.

I would like to reuse some of your configuration code, so I am asking you: Could you add a license to this repository? A permissive license such as MIT or one of the Creative Commons licenses would be nice.

**Comment by ryantking** [comment]
**TLDR:** Added an unlicense, do as you will with the code.

Hello, thanks for your kind words about the repo! Since a lot of the code is cobbled together from other sources with varying levels of modification, I don't want to add any additional licensing such as an MIT or CC. Because of this I have added the unlicense to give full permissions to anyone who wants to do the same with my repo. Anything in this repo that is useful/cool enough to license I will eventually move to its own repo with an MIT or GPL or something.

**Comment by akirak** [comment]
Thank you! Makes sense.
